shell:
  program: /usr/bin/env
  args:
    - zsh
    - -l
    - -c
    - sleep 0.01; zellij attach --index 0 || zellij

window:
  opacity: 0.90
  decorations: none
  padding:
    x: 6 
    y: 6

font:
  normal:
    family: FiraCode Nerd Font
    style: Regular
  size: 12

colors:
  primary:
    background: "#07080a"
    foreground: "#eef1f5"
    dim_foreground: "#eef1f5"
    bright_foreground: "#eef1f5"

  cursor:
    text: "#07080a"
    cursor: "#eef1f5"
  vi_mode_cursor:
    text: "#07080a"
    cursor: "#eef1f5"

  search:
    matches:
      foreground: "#07080a"
      background: "#D8DEE9"
    focused_match:
      foreground: "#07080a"
      background: "#228b22"
    footer_bar:
      foreground: "#07080a"
      background: "#D8DEE9"

  # Keyboard regex hints
  hints:
    start:
      foreground: "#07080a"
      background: "#d2691e"
    end:
      foreground: "#07080a"
      background: "#D8DEE9"

  selection:
    text: "#07080a"
    background: "#D8DEE9"

  normal:
    black: "#07080a"
    red: "#d21e24"
    green: "#228b22"
    yellow: "#d2691e"
    blue: "#3a5fd4"
    magenta: "#663399"
    cyan: "#008b8b"
    white: "#eef1f5"

  bright:
    black: "#181b22"
    red: "#d21e24"
    green: "#228b22"
    yellow: "#daa520"
    blue: "#3a5fd4"
    magenta: "#663399"
    cyan: "#008b8b"
    white: "#eef1f5"

  dim:
    black: "#181b22"
    red: "#dc141b"
    green: "#228b22"
    yellow: "#daa520"
    blue: "#3a5fd4"
    magenta: "#663399"
    cyan: "#008b8b"
    white: "#FAFAFA"
