return {
  'navarasu/onedark.nvim',
  priority = 1000,
  init = function()
    require('onedark').setup {
      style = 'deep',
      colors = {
        -- black = "#0e1013",
        bg0 = '#010909',
        -- bg1 = "#21283b",
        -- bg2 = "#283347",
        -- bg3 = "#2a324a",
        -- bg_d = "#141b24",
        -- bg_blue = "#54b0fd",
        -- bg_yellow = "#f2cc81",
        -- fg = "#93a4c3",
        red = '#bb2525',
        green = '#449944',
        orange = '#d86818',
        yellow = '#daa520',
        blue = '#3a5fd4',
        purple = '#8855bb',
        cyan = '#00abab',
        -- grey = "#455574",
        -- light_grey = "#6c7d9c",
        -- dark_cyan = "#1b6a73",
        -- dark_red = "#992525",
        -- dark_yellow = "#8f610d",
        dark_purple = '#552288',
        diff_add = '#002800',
        diff_delete = '#3f0001',
        diff_change = '#291c00',
        diff_text = '#493706',
        -- diff_text = '#493706',
      },
      highlights = {
        NormalFloat = { fg = '$fg', bg = 'none' },
        FloatBorder = { fg = '$dark_purple', bg = 'none' },
        FloatTitle = { fg = '$red' },
        CursorLine = { bg = '$bg_d' },
        Visual = { bg = '$bg_d' },
        IblScope = { fg = '$dark_purple', fmt = 'nocombine' },
        TelescopePromptBorder = { fg = '$dark_purple' },
        TelescopeResultsBorder = { fg = '$dark_purple' },
        TelescopePreviewBorder = { fg = '$dark_purple' },
        TelescopeSelection = { bg = '$bg_d' },
        NavbuddyNormalFloat = { fg = '$dark_purple', bg = 'none' },
        MiniJump = { fg = 'white', bg = '$dark_purple' },
        BufferLineFill = { bg = '$bg1' },
        BufferLineBackground = { bg = '$bg_d' },
        BufferLineBufferSelected = { bg = '$bg0' },
        BufferLineBufferVisible = { bg = '$bg0' },
        BufferLineIndicatorSelected = { fg = '$orange', bg = '$bg0' },
        BufferLineIndicatorVisible = { fg = '$orange', bg = '$bg0' },
        BufferLineNumbers = { fg = '$orange', bg = '$bg_d' },
        BufferLineNumbersSelected = { fg = '$orange', bg = '$bg0' },
        BufferLineNumbersVisible = { fg = '$orange', bg = '$bg0' },
        BufferLineModified = { fg = '$green', bg = '$bg_d' },
        BufferLineModifiedSelected = { fg = '$green', bg = '$bg0' },
        BufferLineModifiedVisible = { fg = '$green', bg = '$bg0' },
        BufferLineGroupSeparator = { bg = '$bg_d' },
        BufferLineGroupLabel = { fg = '$fg', bg = '$bg_d' },
      },
    }
    require('onedark').load()
  end,
}

-- vim: ts=2 sts=2 sw=2 et
