# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "none";
      fsType = "tmpfs";
    };

  fileSystems."/boot" =
    { device = lib.mkForce "/dev/disk/by-uuid/F7B1-2B87";
      fsType = "vfat";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/9c268980-3c92-4841-8c6f-dd2eaddfea0a";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  boot.initrd.luks.devices."crypted-main".device = "/dev/disk/by-uuid/f3de7af6-fc84-4ed4-90d7-3d8af379fe8b";

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/9c268980-3c92-4841-8c6f-dd2eaddfea0a";
      fsType = "btrfs";
      options = [ "subvol=@nix" ];
    };

  fileSystems."/state" =
    { device = "/dev/disk/by-uuid/9c268980-3c92-4841-8c6f-dd2eaddfea0a";
      fsType = "btrfs";
      options = [ "subvol=@state" ];
    };

  fileSystems."/tmp" =
    { device = "/dev/disk/by-uuid/9c268980-3c92-4841-8c6f-dd2eaddfea0a";
      fsType = "btrfs";
      options = [ "subvol=@tmp" ];
    };

  fileSystems."/var/logs" =
    { device = "/dev/disk/by-uuid/9c268980-3c92-4841-8c6f-dd2eaddfea0a";
      fsType = "btrfs";
      options = [ "subvol=@logs" ];
    };

  fileSystems."/vol/media" =
    { device = "/dev/disk/by-uuid/799bc1f9-776c-4ab2-90c9-71b568bd4e0a";
      fsType = "btrfs";
    };

  boot.initrd.luks.devices."crypted-media".device = "/dev/disk/by-uuid/fd4d6106-e047-4e90-85e1-1acf728b9566";

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp2s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp3s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
