return {
  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = "onedark",
    },
  },
  {
    "navarasu/onedark.nvim",
    lazy = false,
    priority = 1000,
    init = function()
      require("onedark").setup({
        style = "deep",
        colors = {
          black = "#010909",
          bg0 = "#010909",
          bg1 = "#1B2B2B",
          bg2 = "#283C3C",
          bg3 = "#364D4D",
          bg_d = "#0E1A1A",
          bg_blue = "#2757d6",
          bg_yellow = "#efbd5d",
          fg = "#f3f7f8",
          red = "#bb2525",
          green = "#128c21",
          orange = "#d86818",
          yellow = "#daa520",
          blue = "#2757d6",
          purple = "#8855bb",
          cyan = "#00abab",
          grey = "#435d5d",
          light_grey = "#8A9B9B",
          dark_cyan = "#00abab",
          dark_red = "#bb2525",
          dark_yellow = "#daa520",
          dark_purple = "#8855bb",
          diff_add = "#083D13",
          diff_delete = "#491313",
          diff_change = "#2A1B0C",
          diff_text = "#574712",
        },
        highlights = {
          NormalFloat = { fg = "$fg", bg = "none" },
          FloatBorder = { fg = "$green", bg = "none" },
          FloatTitle = { fg = "$red" },
          CursorLine = { bg = "$bg_d" },
          Visual = { bg = "$bg_d" },
          -- IblScope = { fg = '$dark_purple', fmt = 'nocombine' },
          -- NavbuddyNormalFloat = { fg = '$dark_purple', bg = 'none' },
          -- MiniJump = { fg = 'white', bg = '$dark_purple' },

          -- SnacksDashboardHeader = { fg = "$green" },
          -- SnacksDashboardKey = { fg = "$orange" },
          -- SnacksPickerBorder = { fg = "$green" },

          BufferLineBufferSelected = { fg = "$fg", bg = "$bg0" },
          BufferLineBufferVisible = { fg = "$fg", bg = "$bg0" },
          BufferLineIndicatorSelected = { fg = "$orange", bg = "$bg0" },
          BufferLineIndicatorVisible = { fg = "$bg0", bg = "$bg0" },
          BufferLineNumbers = { fg = "$orange" },
          BufferLineNumbersSelected = { fg = "$orange", bg = "$bg0" },
          BufferLineNumbersVisible = { fg = "$orange", bg = "$bg0" },
          BufferLineModifiedSelected = { fg = "$green", bg = "$bg0" },
          BufferLineModifiedVisible = { fg = "$green", bg = "$bg0" },
          BufferLineDiagnosticsSelected = { bg = "$bg0" },
          BufferLineDiagnosticsVisible = { bg = "$bg0" },
          BufferLineCloseButtonSelected = { bg = "$bg0" },
          BufferLineCloseButtonVisible = { bg = "$bg0" },
          BufferLineHintSelected = { fg = "$purple", bg = "$bg0" },
          BufferLineHintVisible = { fg = "$purple", bg = "$bg0" },
          BufferLineInfoSelected = { fg = "$blue", bg = "$bg0" },
          BufferLineInfoVisible = { fg = "$blue", bg = "$bg0" },
          BufferLineWarningSelected = { fg = "$yellow", bg = "$bg0" },
          BufferLineWarningVisible = { fg = "$yellow", bg = "$bg0" },
          BufferLineErrorSelected = { fg = "$red", bg = "$bg0" },
          BufferLineErrorVisible = { fg = "$red", bg = "$bg0" },
        },
      })
      require("onedark").load()
    end,
  },
}
