return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "bash",
      "c",
      "cpp",
      "css",
      "diff",
      "dockerfile",
      "gitignore",
      "gitcommit",
      "git_rebase",
      "json5",
      "just",
      "kdl",
      "lua",
      "luadoc",
      "luap",
      "markdown",
      "markdown_inline",
      "printf",
      "query",
      "regex",
      "sql",
      "toml",
      "vim",
      "vimdoc",
      "yaml",
      "zig",
    },
  },
}
