#!/bin/bash

# Show a fuzzy-finder TUI for picking new Arch packages to install.
# https://github.com/basecamp/omarchy/blob/dev/bin/omarchy-pkg-install

set -euo pipefail

fzf_args=(
  --multi
  --preview 'paru -Sii {1}'
  --preview-label='alt-p: toggle description, alt-j/k: scroll, tab: multi-select'
  --preview-label-pos='bottom'
  --preview-window 'down:65%:wrap'
  --bind 'alt-p:toggle-preview'
  --bind 'alt-d:preview-half-page-down,alt-u:preview-half-page-up'
  --bind 'alt-k:preview-up,alt-j:preview-down'
  --color 'pointer:green,marker:green'
)

pkg_names=$(pacman -Slq | fzf "${fzf_args[@]}")
echo $pkg_names

if [[ -n "$pkg_names" ]]; then
 # Convert newline-separated selections to space-separated for yay
 echo "$pkg_names" | tr '\n' ' ' | xargs sudo paru -S --noconfirm
 show-done
fi
